### ISSUE TITLE
Won't work with scss files.

### ISSUE THREAD

**Issue by acupofspirt** [mrmlnc/vscode-csscomb#1]
This plugin doesn't work with .scss files at all. It works only with .css.
And is there any command for keyboard shortcuts?

**Comment by mrmlnc** [comment]
Thanks for issue! Unfortunately, the VS Code does not distinguish between Sass and Scss syntax. The new version introduces support for Scss as fallback for Sass. 

To add support for keyboard shortcuts, create a new rule in `File -> Preferences -> Keyboard Shortcuts`:

```json
{
  "key": "ctrl+shift+c",
  "command": "csscomb.processEditor"
}
```

**Comment by acupofspirt** [comment]
От души, братан, душевно в душу))

**Comment by HienNguyenAsnet** [comment]
How about this issue. It's still not work on v5.2.1, right?

**Comment by mrmlnc** [comment]
Feel free to create a new issue with detailed information about your problem :)

**Comment by HienNguyenAsnet** [comment]
@mrmlnc I create new issue #96
