### ISSUE TITLE
It's just doesn't work

### ISSUE THREAD

**Issue by mohouyizme** [mrmlnc/vscode-csscomb#100]
### Environment

  * VSCode Version: 1.19.1
  * OS Version: Windows 10 1709

### Actual behavior
It's just doesn't work, I've tried everything!

### Config

```js
// No config
```

**Comment by mrmlnc** [comment]
Hello, @mohouyizme,

My plugin has no default configuration. You can use one of [predefined configs](https://github.com/csscomb/csscomb.js/blob/dev/doc/configuration.md#use-one-of-predefined-configs) or [build your own](https://github.com/csscomb/csscomb.js/blob/dev/doc/configuration.md#create-custom-config). The plugin does nothing if there is no configuration.

**Comment by mohouyizme** [comment]
Ok, thanks for responding!

**Comment by mohouyizme** [comment]
I was missing the config file, I thought that the extension comes with default configs. Anyway thanks for hep!
