### ISSUE TITLE
vue support not working

### ISSUE THREAD

**Issue by beeplin** [mrmlnc/vscode-csscomb#101]
### Environment

  * VSCode Version: ... 1.19.1
  * OS Version: ... windows 10 1709

### Actual behavior
not working for <style> in vue files
...

### Expected behavior

...

### Steps to reproduce

...

### Config
all default except for preset: 'zen' ( or any other presets)
```js
// Paste your configuration here.
  // Auto format on save.
  "csscomb.formatOnSave": false,

  // An optional array of glob-patterns to ignore files on save.
  "csscomb.ignoreFilesOnSave": [],

  // One of the predefined configs (csscomb, yandex, zen) or custom config (object) or path to config.
  "csscomb.preset": "zen",

  // Support embedded CSS into HTML.
  "csscomb.supportEmbeddedStyles": true,

  // Configuration of syntax associations.
  "csscomb.syntaxAssociations": {},
```

**Comment by mrmlnc** [comment]
Hello, @beeplin,

You can provide code sample for reproduce your problem?

**Comment by beeplin** [comment]
ooops, I restarted my computer and  tested again and now it works. don't know why. Anyway, never mind. :) I am gonna close this. sorry~
