### ISSUE TITLE
Поддержка PostCSS

### ISSUE THREAD

**Issue by tony-show** [mrmlnc/vscode-csscomb#102]
Здравствуйте! У вас в описании есть установка ассоциаций файлов postcss в scss, но после установки данной настройки есть проблема при компиляции файлов postcss в котором прописан синтаксис cssnext (css4), а конкретно :root { --var: #000; } переменных, происходит ошибка компиляции.

Можно ли как-то обойти данную ошибку (может прописать настройки какие)?
И будет ли внедрятся поддержка PostCSS?

Спасибо!

**Comment by mrmlnc** [comment]
Привет,

Этот репозиторий относится к плагину для редактора VS Code. Всё что мы здесь делаем – вызываем пакет `csscomb` с нужными параметрами. К сожалению, кажется, что **csscomb** не поддерживает CSS4 (не берусь утверждать).

Вот правильный репозиторий:

https://github.com/csscomb/csscomb.js

Твоя проблема воспроизводится, если использовать CSSComb, как CLI-утилиту?
