### ISSUE TITLE
styled-components support

### ISSUE THREAD

**Issue by ApacheEx** [mrmlnc/vscode-csscomb#104]
### Environment

  * VSCode Version: 1.21.0
  * OS Version: MacOS High Sierra 10.13.3

### Actual behavior

![image](https://user-images.githubusercontent.com/1918108/37310723-825fc4c4-264d-11e8-8fa4-cdaa33100622.png)

### Expected behavior

should work here:
![image](https://user-images.githubusercontent.com/1918108/37310785-c21f2104-264d-11e8-9233-9ae6b4eed80b.png)

### Steps to reproduce

try to execute csscomb on js file where styled-components used.

### Config

it doesn't work with any config.

### Question
any chance to have this in near future? or perhaps add a possibility to run csscomb with selection

**Comment by mrmlnc** [comment]
Sorry, but we do not support CSS in JS. You can leave your issue in the CSSComb repository ( https://github.com/csscomb/csscomb.js/issues).
