### ISSUE TITLE
Mixins in LESS are not formatted correctly

### ISSUE THREAD

**Issue by cnshenj** [mrmlnc/vscode-csscomb#105]
### Environment

  * VSCode Version: 1.21.1
  * OS Version: Windows 10 x64

### Actual behavior
```
.mixin {
    overflow-wrap: break-word;
}
.my-class {
    color: #fff;

.mixin();
}
```
### Expected behavior
```
.mixin {
    overflow-wrap: break-word;
}
.my-class {
    color: #fff;

    .mixin();
}
```
### Steps to reproduce
Run `CSSComb: Format styles`

Note: Mixins in LESS can be invoked without `()` too, e.g. `.mixin;`.

**Comment by mrmlnc** [comment]
Hello, @cnshenj,

This is a bug of CSSComb. We use latest version of CSSComb and it can be reproduced with CSSComb as CLI. You can create issue in the [CSSComb repository](https://github.com/csscomb/csscomb.js) and after bump CSSComb version I'll update my plugin 👍
