### ISSUE TITLE
command 'csscomb.execute' not found

### ISSUE THREAD

**Issue by frux** [mrmlnc/vscode-csscomb#108]
### Environment

  * VSCode Version: 1.22.2
  * OS Version: MacOS High Sierra 10.13.4

### Actual behavior

Plugin does format code

### Expected behavior

Plugin doesn't format code. VSCode shows error `command 'csscomb.execute' not found`.

### Steps to reproduce

1. Install plugin vscode-csscomb.
2. Run formatting.

### Config

```json
    "csscomb.preset": "yandex",
    "csscomb.formatOnSave": true,
```
![screencast 2018-05-03 10-52-55](https://user-images.githubusercontent.com/4231003/39561798-76869974-4ec1-11e8-813c-a9de01c191cb.gif)

**Comment by mrmlnc** [comment]
Hello, @frux,

Works fine for me with VS Code `v1.23.0`. 

You can provide more information about your editor settings, output from `Developer Tools` after broken command and list of installed extensions.

**Comment by frux** [comment]
In developer tools console I see
```
notificationsAlerts.ts:39 command 'csscomb.execute' not found
e.onDidNotificationChange @ notificationsAlerts.ts:39
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.error @ notificationService.ts:61
t.onError @ commandsHandler.ts:326
(anonymous) @ commandsHandler.ts:311
done @ winjs.base.js:1393
(anonymous) @ commandsHandler.ts:307
done @ winjs.base.js:1539
g @ winjs.base.js:1195
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
```

List of installed plugins:
```js
[
    "auto-rename-tag",
    "babelrc",
    "bracket-pair-colorizer",
    "code-settings-sync",
    "EditorConfig",
    "gitflow",
    "gitignore",
    "gitlens",
    "material-icon-theme",
    "npm-intellisense",
    "path-autocomplete",
    "postcss",
    "stylelint",
    "touchbar-command-palette",
    "tslint",
    "vscode-csscomb",
    "vscode-docker",
    "vscode-eslint",
    "vscode-jumpy",
    "vscode-open",
    "vscode-snazzy-operator",
    "vscode-stylefmt",
    "vscode-theme-superonedark",
    "vscode-todo-highlight"
]
```

**Comment by mrmlnc** [comment]
It looks like the problem is in the environment. Unfortunately, I can't help you here.
