### ISSUE TITLE
cursor reset position on formatonsave

### ISSUE THREAD

**Issue by ctf0** [mrmlnc/vscode-csscomb#110]
### Environment

  * VSCode Version: 1.23.1
  * OS Version: 10.11.6

### Actual behavior

using formatonsave will reset the cursor to the end of file

### Expected behavior

cursor position shouldnt change, same as when running the `csscomp format style command`

### Steps to reproduce
`"csscomb.formatOnSave": true,`

**Comment by ryanbowden** [comment]
Any reason for closing this?

**Comment by tfritsch-km** [comment]
Same here, vscode 1.24.1, win 10
@ctf0 could you explain why this issue has been closed ?

**Comment by ctf0** [comment]
@tfritsch-km stopped using vscode

**Comment by tfritsch-km** [comment]
ok thanks for explanations
since the bug still exists, could we reopen the issue ? @ryanbowden can you do that ?

**Comment by tfritsch-km** [comment]
I also noticed it unfolds every folded sections.
