### ISSUE TITLE
formatonsave moves cursor at end of file and unfolds every section

### ISSUE THREAD

**Issue by tfritsch-km** [mrmlnc/vscode-csscomb#112]
### Environment

  * VSCode Version: 1.24.1
  * OS Version: Win 10

### Actual behavior

When `formatonsave` is activated, saving the file places the cursor at the very end of the file, forcing the user to manually move the cursor back to its initial position. 
The folded sections also gets unfolded, which makes it even more difficult to go back to initial position when working on large css files

### Expected behavior

when `formatonsave` is activated, saving the file should not change the cursor position, it should remain on the line that it was on. 

### Steps to reproduce
1. configure vscode csscomb to formatonsave
2. create a css file and type css code into it
3. save file
![issue-vscode-csscomb](https://user-images.githubusercontent.com/10920280/42168660-e0e46e84-7e11-11e8-82dd-5b75944e297f.gif)

### Config
```js
"csscomb.formatOnSave": true,
```

Note: 
this issue is there because a previous issue was closed by the reporter but never worked on : https://github.com/mrmlnc/vscode-csscomb/issues/110

**Edit : this issue doesn't occur when formatOnSave is false and you run command "CSSComb: Format styles" from command palette (CTRL+SHIFT+p).**

**Comment by muuvmuuv** [comment]
@mrmlnc really need a fix for this... it is annoying. Do you have any clue what is doing this? If you have no time and know where to start, I will try my best to make a PR to fix this.

**Comment by muuvmuuv** [comment]
This might help: https://github.com/Microsoft/vscode/issues/111

**Comment by nealoke** [comment]
@tfritsch-km any way I can help solve this?

**Comment by tfritsch-km** [comment]
Sorry @nealoke, I really don't know.
Maybe ask @mrmlnc where to start (I haven't digged into the code of this plugin yet)

**Comment by nealoke** [comment]
Aah oops, I thought you were the author, @mrmlnc  how can I help with this plugin? :)

**Comment by tfritsch-km** [comment]
no problem 😄

**Comment by tfritsch-km** [comment]
I tried to look at it, and noticed that the code that formats css is slightly different when saving file from the one that runs when formatting with the "CSSComb: Format styles" command : 

on "CSSComb: Format styles" command :
https://github.com/mrmlnc/vscode-csscomb/blob/65c71c40c8a5dedac9b408e7fa158e8b864ea057/src/extension.ts#L69

on save :
https://github.com/mrmlnc/vscode-csscomb/blob/65c71c40c8a5dedac9b408e7fa158e8b864ea057/src/extension.ts#L118

I don't know the difference between the two, anyone that knows vscode api sees something interesting ?

**Comment by mrmlnc** [comment]
Hey,

Unfortunately, now I don't have free time to support this plugin. When I developed this plugin it was not possible to save the cursor position when we use `event.waitUntil(actions)`. If you want to correct the current behavior, please send a pull request.

**Comment by tfritsch-km** [comment]
Thank you @mrmlnc 
I just did a PR, could you review it ? I haven't heavily tested it but it seems to work. Any advice on it ?

**Comment by tfritsch-km** [comment]
Hey,
I've used the patch for about a week now, and it works fine so far, I didn't notice any regression. Would love to get some feedback.

**Comment by nealoke** [comment]
@mrmlnc could you please merge this?

**Comment by nealoke** [comment]
🙏  merge please 😄

**Comment by aldenfbrown** [comment]
+1 🙏 merge please 😄

**Comment by tfritsch-km** [comment]
Hello,
As @mrmlnc said in the PR comments (see https://github.com/mrmlnc/vscode-csscomb/pull/116#issuecomment-422672084) , there is a regression in my code when using the `File: Save all` command : only the focused editor gets formatted. This PR could however be merged if it gets a config option to enabled it, but I unfortunately have no time to work on it ATM. 😕

**Comment by tfritsch-km** [comment]
So, I just pushed a new commit to PR that should make it work event with `File > save all`, I hope it produces no regressions this time 😃

**Comment by zoreet** [comment]
@mrmlnc what's holding up this merge?

**Comment by mrmlnc** [comment]
Fixed by https://github.com/mrmlnc/vscode-csscomb/releases/tag/5.2.3. @tfritsch-km, thanks a lot.
