### ISSUE TITLE
Error when using css variables in scss files.

### ISSUE THREAD

**Issue by jb-trm** [mrmlnc/vscode-csscomb#119]
I think csscomb should support css variables by now, so this seems to be a plugin specific error?

### Environment

  * VSCode Version: 1.27.2
  * OS Version: OSX 10.13.6

### Actual behavior
[CSSComb]

Parsing error: /Users/tommymathiesen/Sites/Kirby/designsystem/src/styles.scss
Please check validity of the block starting from line #45
CSScomb Core version: 4.2.0

44 | :root{ 
45*|   --ion-font-family: "Effra";
46 |   font-family: var(--ion-font-family);
47 | }

Syntax: scss
Gonzales PE version: 3.4.7
...

### Expected behavior
Validate and insert space after :root
...

### Steps to reproduce

...

### Config
```
{
  "remove-empty-rulesets": true,
  "always-semicolon": true,
  "color-case": "lower",
  "block-indent": "  ",
  "element-case": "lower",
  "eof-newline": true,
  "leading-zero": true,
  "quotes": "single",
  "sort-order-fallback": "abc",
  "space-before-colon": "",
  "space-after-colon": " ",
  "space-before-combinator": " ",
  "space-after-combinator": " ",
  "space-between-declarations": "\n",
  "space-before-opening-brace": " ",
  "space-after-opening-brace": "\n",
  "space-after-selector-delimiter": "\n",
  "space-before-selector-delimiter": "",
  "space-before-closing-brace": "\n",
  "strip-spaces": true,
  "tab-size": true,
  "vendor-prefix-align": true
}```

**Comment by mrmlnc** [comment]
Hello, @jb-trm,

It's looks like a bug of CSSComb. We use latest version of CSSComb and most likely it can be reproduced with CSSComb as CLI. You can create issue in the [CSSComb repository](https://github.com/csscomb/csscomb.js) and after bump CSSComb version I'll update my plugin 👍

**Comment by Genenenenaam** [comment]
CSSComb did a fix. Is this plugin updated yet?

**Comment by dm-naumenkov** [comment]
> CSSComb did a fix. Is this plugin updated yet?

The plugin hasn't been updated. I had to update the plugin myself. Take advantage of it.
https://marketplace.visualstudio.com/items?itemName=naumstory.vscode-csscomb

**Comment by mrmlnc** [comment]
Unfortunately, the new version of CSSComb has no effect for this problem.

```js
const Comb = require('csscomb');

(async () => {
	try {
		const comb = new Comb('csscomb');

		const res = await comb.processPath('./smoke/test.css');

		console.dir(res, { colors: true });
	} catch (error) {
		console.dir(error, { colors: true });
	}
})();
```

This is work correctly if you drop the `sort-order` property:

```js
const Comb = require('csscomb');

(async () => {
	try {
		const config = Comb.getConfig('csscomb');

		delete config['sort-order'];

		const comb = new Comb(config);

		const res = await comb.processPath('./smoke/test.css');

		console.dir(res, { colors: true });
	} catch (error) {
		console.dir(error, { colors: true });
	}
})();
```

**Comment by naumstory** [comment]
mrmlnc, https://github.com/avdieiev/csscomb.js/commit/dfb352330b13218887f584bb2fdb9ec00cf67421

**Comment by mrmlnc** [comment]
As you can see (https://github.com/csscomb/csscomb.js/commits/dev) this is unpublished version right now.

**Comment by naumstory** [comment]
mrmlnc, I'm sorry, I sent the wrong link. https://github.com/csscomb/csscomb.js/pull/595

Everything works in this plugin (https://marketplace.visualstudio.com/items?itemName=naumstory.vscode-csscomb), because it simply updates the dependence
