### ISSUE TITLE
The "sort-order-fallback": "abs" setting does not work

### ISSUE THREAD

**Issue by Ruslan-Aleev** [mrmlnc/vscode-csscomb#121]
### Environment

  * VSCode Version: 1.32.3
  * OS Version: Windows_NT x64 6.1.7601 (Windows 7)

### Actual behavior
**Before csscomb:**
![before](https://user-images.githubusercontent.com/12523676/54544157-70652e00-49b8-11e9-9a7e-6f5ab0ab541e.png)

**After csscomb:**
![after](https://user-images.githubusercontent.com/12523676/54544165-73f8b500-49b8-11e9-9de3-70f8781e29de.png)

The code is aligned, 0px becomes 0, but the "sort-order-fallback" setting is ignored.

### Config

```js
// Paste your configuration here.
{
    "remove-empty-rulesets": true,
    "always-semicolon": true,
    "color-case": "lower",
    "block-indent": "    ",
    "color-shorthand": true,
    "element-case": "lower",
    "eof-newline": false,
    "leading-zero": false,
    "quotes": "single",
    "sort-order-fallback": "abc",
    "space-before-colon": "",
    "space-after-colon": " ",
    "space-before-combinator": " ",
    "space-after-combinator": " ",
    "space-between-declarations": "\n",
    "space-before-opening-brace": " ",
    "space-after-opening-brace": "\n",
    "space-after-selector-delimiter": " ",
    "space-before-selector-delimiter": "",
    "space-before-closing-brace": "\n",
    "strip-spaces": true,
    "tab-size": true,
    "unitless-zero": true,
    "vendor-prefix-align": true
}
```

**Comment by mrmlnc** [comment]
Hello, @Ruslan-Aleev,

It's looks like a bug of CSSComb. We use latest version of CSSComb and most likely it can be reproduced with CSSComb as CLI. You can create issue in the [CSSComb repository](https://github.com/csscomb/csscomb.js) and after bump CSSComb version I'll update my plugin 👍 

Also, please, never post code as image :)

**Comment by Ruslan-Aleev** [comment]
Hello, @mrmlnc  I think you're wrong about the bug in the csscomb, because in SublimeText3, everything is sorted normally and there is no such bug.
