### ISSUE TITLE
What should I am going to do?

### ISSUE THREAD

**Issue by DWYW** [mrmlnc/vscode-csscomb#127]
### Environment

  * VSCode Version: ...
  * OS Version: ...
版本: 1.39.2
提交: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
日期: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

### Actual behavior
![image](https://user-images.githubusercontent.com/19439805/67145057-45c1b780-f2b0-11e9-80eb-82444475f3ff.png)

...

### Expected behavior

...

### Steps to reproduce

...

### Config

```js
// Paste your configuration here.
```

**Comment by mrmlnc** [comment]
Hello, @DWYW,

It's looks like a bug of CSSComb. We use latest version of CSSComb and most likely it can be reproduced with CSSComb as CLI. You can create issue in the [CSSComb repository](https://github.com/csscomb/csscomb.js) and after bump CSSComb version I'll update my plugin 👍
