### ISSUE TITLE
The csscomb make css attributes be one line when the linefeed is CRLF

### ISSUE THREAD

**Issue by muhouhuanghun** [mrmlnc/vscode-csscomb#129]
### Environment

  * VSCode Version: 1.41.1 (user setup)
  * OS Version: Windows_NT x64 10.0.18362

### Actual behavior
I create a new file in the windows, and I use the csscomb to format the css code.
But the css attributes always be one line. 
when i set the linefeed to LF, everything is ok.

**Comment by mrmlnc** [comment]
Hello, @muhouhuanghun,

It's looks like a bug of CSSComb or something with your configuration. We use latest version of CSSComb and most likely it can be reproduced with CSSComb as CLI. You can create issue in the [CSSComb repository](https://github.com/csscomb/csscomb.js) and after bump CSSComb version I'll update my plugin 👍
