### ISSUE TITLE
Crashes on custom properties

### ISSUE THREAD

**Issue by zakaratcha** [mrmlnc/vscode-csscomb#136]
![Снимок экрана от 2020-06-17 22-27-14](https://user-images.githubusercontent.com/2573820/84941713-6b76b900-b0ea-11ea-8b79-6208257dc2d6.png)

Это ошибка самого `csscomb` версии `4.3.0`. Причём в `dev` ветке этот баг давно закрыт, но новую версию `csscomb` почему-то никак не выпустят.
Если в `package.json` заменить
```json
  "csscomb": "4.3.0"
```
на
```json
  "csscomb": "github:csscomb/csscomb.js#ce7ad831bd9b7fddb660c59afbbaf183c98d6ca7"
```
то должно помочь

**Comment by mrmlnc** [comment]
Closing in favor of #137.
