### ISSUE TITLE
Fails on nested child selector (CSScomb issue)

### ISSUE THREAD

**Issue by arlodesign** [mrmlnc/vscode-csscomb#16]
vscode 1.5.2
vscode-csscomb 2.0.0
Mac OS X 10.11.6

Here's a GIF of it not working in a .scss file and it working in a .css file (note the `&._block {}` rules that aren't changing):

![screen recording 2016-09-13 at 11 46 am](https://cloud.githubusercontent.com/assets/201878/18483044/3017a55e-79a8-11e6-9ac8-90ecff688895.gif)

What other information can I provide? I'm currently running node 6.5.0, if that makes a difference (not sure if it does).

**Comment by mrmlnc** [comment]
Hello, @arlodesign,

You see something in the console (`Help -> Toggle Developer Tools`)?

**Comment by arlodesign** [comment]
(I didn't know I could turn that on. NEAT.) Looks like it might be an issue in CSSComb itself, actually.

![console errors](https://cl.ly/1Z3r440f0m14/Image%202016-09-13%20at%2011.56.00%20AM.png)

**Comment by mrmlnc** [comment]
Unfortunately, yes, this is the problem inside CSScomb.

You can provide minimal code example that causes an error?

**Comment by arlodesign** [comment]
I found the culprit. It's a nested `>`:

```scss
div {
	display: flex;

	> * {
		flex: 1;
	}
}
```

If I put a `&` in front of the `>`, it's fine.

It wasn't working on _any_ of the sass files I tested it on—we must use that a lot. 😊

**Comment by mrmlnc** [comment]
Well, it's bug in **csscomb-4.0.0-alpha**, but **csscomb-3.1.8** works fine. I can provide the option to select the version of CSScomb (`useOldCore: Boolean`). But the old version does not support some options.

I think you need to create an issue in the main repository (https://github.com/csscomb/csscomb.js).

Let me know if you are satisfied with this offer or you are already using a different extension.

**Comment by danieloprado** [comment]
+1

**Comment by mrmlnc** [comment]
@bgiraffe, @arlodesign, @danieloprado,

Please, try `useLegacyCore` option in vscode-csscomb **2.1.0**.

===

If you use this extension and satisfied with his work, then please leave a review in the marketplace.

**Comment by bgiraffe** [comment]
Thank you, it work like a charm, great work!

**Comment by arlodesign** [comment]
Awesome. :+1:

**Comment by arlodesign** [comment]
It's an open issue in gonzales-pe: https://github.com/tonyganch/gonzales-pe/issues/130
