### ISSUE TITLE
Problem with custom .csscomb.json

### ISSUE THREAD

**Issue by StfBauer** [mrmlnc/vscode-csscomb#18]
Hi, I insert the following CSSComb configuration file. After that csscomb in visual studio doesn't work anymore.

Any suggestions?

[csscomb.txt](https://github.com/mrmlnc/vscode-csscomb/files/491087/csscomb.txt)

**Comment by mrmlnc** [comment]
Hello, @StfBauer,

Please, try to:

  * Set `csscomb.useLegacyCore: true` option.
  * <kbd>F1</kbd> -> `Reload Window`
  * Run the CSScomb command again.

**Comment by mrmlnc** [comment]
Also you can just remove `"eof-newline": false` option from config.

**Comment by StfBauer** [comment]
Thank works so far.. ;)

**Comment by mrmlnc** [comment]
In next version of this plugin we will return to the old version of CSSComb. Please, see https://github.com/mrmlnc/vscode-csscomb/pull/23#issuecomment-252422427
