### ISSUE TITLE
Adopt formatOnSave changes

### ISSUE THREAD

**Issue by jrieken** [mrmlnc/vscode-csscomb#26]
Related to https://github.com/mrmlnc/vscode-stylefmt/issues/28, I'd recommend to rely on the new *format on save*-feature. It will reduce the risk of endless event-write-event-write loops and be a neater integration

**Comment by ryanbowden** [comment]
Are you sure it does not already support this? As I have my SCSS files being watched by a gulp task and it only sees one write when I use this.

**Comment by jrieken** [comment]
Actually, true. Didn't see that is already is `onWillSaveTextDocument`. Thanks for catching this.
