### ISSUE TITLE
Support for Polymer Web Components

### ISSUE THREAD

**Issue by abdonrd** [mrmlnc/vscode-csscomb#30]
If I use the plugin in a Polymer element, the plugin doesn't work:

`TypeError: Cannot read property 'range' of undefined`

**Comment by mrmlnc** [comment]
Hello, @abdonrd,

Firstly, I'm sorry that you are having problems with this plugin.

Unfortunately, I need more information about what is happening. For example, minimal code example. 

🐼

**Comment by abdonrd** [comment]
Sure! Sorry @mrmlnc!

For example, check the [ibm-toolbar.html](https://github.com/IBMResearch/ibm-toolbar/blob/master/ibm-toolbar.html) element.

**Comment by mrmlnc** [comment]
I will work on this issue tomorrow morning (Russia, GMT+3).

**Comment by abdonrd** [comment]
Thanks!

**Comment by mrmlnc** [comment]
Well, I researched the errors and have a bad result:

  * CSSComb not supported CSS built-in into HTML. I can search `style` tag and if it is found, run CSSComb. But it looks like a Hack.

**Comment by abdonrd** [comment]
Thanks for the research!

You're going to add search `style` tags? Or we should create an issue in the CSSComb repo?

**Comment by mrmlnc** [comment]
> Or we should create an issue in the CSSComb repo?

Nope, CSSComb is tool only for CSS, Less, Sass (+SCSS). 

> You're going to add search `style` tags? 

Yes, I wrote code, but now I have problems with identation (because we should calculate new indentation for CSS (as nested HTML `style` tag + CSS))

I moved this issue to monday or tuesday.

**Comment by abdonrd** [comment]
Ok, thanks! :)

**Comment by mrmlnc** [comment]
See 3.1.0.

**Comment by abdonrd** [comment]
Thanks @mrmlnc!

How it should work? I use:

![screen shot 2016-10-25 at 10 44 23](https://cloud.githubusercontent.com/assets/1007051/19678912/072b59e2-9aa0-11e6-9214-ad9d3130e482.png)

But I no see changes.

**Comment by mrmlnc** [comment]
@abdonrd,

Just tun `CSSComb: Format styles` .

![2016-10-25_11-46-56](https://cloud.githubusercontent.com/assets/7034281/19678988/c03e1b7e-9aa8-11e6-80b0-3668cca67d21.gif)

**Comment by mrmlnc** [comment]
You have CSSComb config?

**Comment by abdonrd** [comment]
I have a `.csscomb.json` file at root of the project.

**Comment by mrmlnc** [comment]
@abdonrd,

Please, try 3.1.1 version. And let me know if you have problems.

**Comment by abdonrd** [comment]
@mrmlnc better, but now moves the CSS to left. :/

**Comment by mrmlnc** [comment]
@abdonrd,

I pushed relase with 3.1.2 version. Please, try it.

Sorry for this situation.

**Comment by abdonrd** [comment]
Yaay! It works, thanks so much @mrmlnc!

**Comment by abdonrd** [comment]
@mrmlnc In the `csscomb.preset` I can set up a file? Like:

`"csscomb.preset": "/Users/abdonrd/Work/.csscomb.json"`

**Comment by mrmlnc** [comment]
@abdonrd,

Now nope, but if you create issue - yes 😅

**Comment by abdonrd** [comment]
Done! https://github.com/mrmlnc/vscode-csscomb/issues/33
