### ISSUE TITLE
TypeError: b.match is not a function

### ISSUE THREAD

**Issue by ryanbowden** [mrmlnc/vscode-csscomb#31]
Just got a weird error,

A SCSS file I just tried to save is vscode when I did got the error 

"TypeError: b.match is not a function" in the output. 

Had a look through the file could not find anything that could be the issue. 

If you want I can PM you the file.

**Comment by mrmlnc** [comment]
Hello, @ryanbowden,

Sorry for this situation, but I think that is CSSComb bug. You can send file to `dmalinochkin@rambler.ru`.

**Comment by ryanbowden** [comment]
Hey @mrmlnc,

I have sent an email with the file that's an issue.

**Comment by mrmlnc** [comment]
@ryanbowden,

Small question: you use `useLatestCore` option?

**Comment by ryanbowden** [comment]
@mrmlnc 

Nope i do not.

**Comment by mrmlnc** [comment]
Well, `4.0.0-alpha` have Error with this file:

```
TypeError: Cannot read property 'is' of null
```

![image](https://cloud.githubusercontent.com/assets/7034281/19683528/3a7cdcce-9abb-11e6-97f3-752d2ed61f4f.png)

Stable core works fine:

![2016-10-25_13-59-56](https://cloud.githubusercontent.com/assets/7034281/19683558/546b0f0c-9abb-11e6-914d-01a70679f376.gif)

**Comment by ryanbowden** [comment]
Found the issue, where we define a gradient we write this:
`$experimental-support-for-svg: true;`
Feel like it a bit of code copied in by mistake. 

But once that was removed it worked, that line causes issue if you set a sort order and that's what i have in the config. 

Cheers for the help.
