### ISSUE TITLE
How to add ignore Files on save

### ISSUE THREAD

**Issue by ryanbowden** [mrmlnc/vscode-csscomb#32]
Sorry if this seems basic but i am trying to add ignore files on save and doing the following

`"csscomb.ignoreFilesOnSave": ['sass/_fonts.scss']`

But getting the error "Expected comma or closing bracket"

Any idea what i am doing wrong, could do with an example on the readme, happy to write that up once I have got it working.

**Comment by mrmlnc** [comment]
Calculation of the path begins from the root directory for currect workspace. Also we use Glob patterns.

If you have following structure:

  * `sass/`
    * `_fonts.scss`

it should works fine.

If you have following structure:

  * `styles/`
    * `sass/`
      * `_fonts.scss`

Should work: `**/sass/_fonts.scss`

**Comment by ryanbowden** [comment]
Yes they are in:

- sass/
- - _fonts.scss

But when i type it in vscode I get a red line under it here a screen shot.

Thats what i have but it not working and still changing the file.

**Comment by mrmlnc** [comment]
> I get a red line under it here a screen shot.

You use double or single quotes?

**Comment by ryanbowden** [comment]
FIXED IT,

Thank you,

Was using single as it says on the example `['variables.less', 'mixins/**/*']`
On the readme file, could do with that being updated (I will do that if you want)

But changing it to double fixed the issue.

**Comment by mrmlnc** [comment]
I will be glad to see PR :)
