### ISSUE TITLE
Getting Cannot read property 'toCSS' of undefined on VS Code 1.7.0

### ISSUE THREAD

**Issue by crdo** [mrmlnc/vscode-csscomb#39]
Not working on 1.7.0 with "Cannot read property 'toCSS' of undefined" error message.

**Comment by mrmlnc** [comment]
Hello, @crdo,

I have few questions for you:

  0. It worked before the upgrade to 1.7.0?
  1. What is written in the Developer Tools Console after run CSSComb command?
  2. You use `useLatestCore` option?
  3. Have you tried to use `useLatestCore` option?
  4. You can send me your file (here or `dmalinochkin@rambler.ru`)

Sorry for this situation, but I think that is CSSComb bug. In the next version I will write an error handler that provides more detailed information.

**Comment by mrmlnc** [comment]
Related to CSSComb.
