### ISSUE TITLE
add search for $HOME dir

### ISSUE THREAD

**Issue by medifle** [mrmlnc/vscode-csscomb#4]
If there is no `.csscomb.json` in current project root, this plugin may look for one in user's $HOME dir.

Therefore many of my project could share a common `.csscomb.json`.

The CSScomb plugin for Sublime Text has supported this feature.

See [here](https://packagecontrol.io/packages/CSScomb)

**Comment by mrmlnc** [comment]
Done. Please, checkout the new version of CSScomb plugin.

```
F1 → ext → Extensions: Show Outdated Extensions -> Update CSScomb plugin
```

I used a native method to determine the home directory from Node.js. If there are any errors-write.

--

Thanks for issue. :+1:
