### ISSUE TITLE
csscomb does not react to .csscomb.json

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [mrmlnc/vscode-csscomb#41]
I have added .csscomb.json file to my home directory and no matter what changes i do .less (and .css) files are not formatted

**Comment by mrmlnc** [comment]
Hello, @vytautas-pranskunas-,

Firstly, thanks that you try to use this plugin and open this Issue.

Unfortunately, I must ask you to provide your config file (`.csscomb.json`) and editor settings for `csscomb`, because without it I wouldn't be able to understand the error.

**Comment by vytautas-pranskunas-** [comment]
i have simply copied stuff from your description 

{
    "csscomb.formatOnSave": true,
    "csscomb.preset": "csscomb",
    "csscomb.preset": {
        "remove-empty-rulesets": true,
        "always-semicolon": true,
        "block-indent": 4
    }
}

tired different variations from no config att all to this you can see  (with only one key csscomb.preset" with to keys like shown and etc )

**Comment by mrmlnc** [comment]
Well, `.csscomb.json` file should contains only `CSSComb` rules - not CSSComb plugin settings. Read more about this in [official CSSComb repository](https://github.com/csscomb/csscomb.js/blob/dev/doc/configuration.md).

For example:

```json
{
  "color-case": "lower"
}
```

**Comment by vytautas-pranskunas-** [comment]
It started to work somehow because I used to try event with one line before: "remove-empty-rulesets": true and it did not work.
and where then goes custom config settings? like: "csscomb.formatOnSave": true,

**Comment by mrmlnc** [comment]
## vscode-csscomb settings (file -> preferences - user settings)

```json
"csscomb.preset": {
  "color-case": "lower"
}
```

\+ any rules from https://github.com/csscomb/csscomb.js/blob/dev/doc/options.md

## `.csscomb.json`

```json
{
  "color-case": "lower"
}
```

\+ any rules from https://github.com/csscomb/csscomb.js/blob/dev/doc/options.md

**Comment by vytautas-pranskunas-** [comment]
So same rules can be applied in 2 places? That's cool. So we can close this ticket.  This part can be documented better. Thanks.
