### ISSUE TITLE
Has recently stopped working when executing comb command

### ISSUE THREAD

**Issue by will-stone** [mrmlnc/vscode-csscomb#49]
Let me know if I can provide any form of diagnostics. Output in VSCode doesn't display anything after running csscomb.

**Comment by mrmlnc** [comment]
Sorry for this situation.

This problem related only for `vscode-csscomb@3.2.6` (`3.2.5` works fine`) version and will be fixed in `4.0.0` version. 

I'll update this extension today.

**Comment by will-stone** [comment]
ok, thanks.

**Comment by mrmlnc** [comment]
**temporary solution**. You can remove `vscode-csscomb` plugin, then download `.vsix` file from https://github.com/mrmlnc/vscode-csscomb/releases/tag/3.2.5 and install it:

![image](https://cloud.githubusercontent.com/assets/7034281/21145216/7af68fd8-c15e-11e6-8f92-d2bc7ada367a.png)

**Comment by will-stone** [comment]
If update is coming soon, I can wait. I'm just mentally tagging my files with "needs combing" at the moment :)

**Comment by mrmlnc** [comment]
Should be fixed in `4.0.0` 👍
