### ISSUE TITLE
feature: add auto format on save

### ISSUE THREAD

**Issue by AnWeber** [mrmlnc/vscode-csscomb#5]
Please add auto format on save. To implement this feature, attach event listener on [vscode.workspace.onDidSaveTextDocument]

Thanks.

**Comment by mrmlnc** [comment]
Good idea! If you have time, you can send a PR or wait until tomorrow (UTC +3 Moscow).

P.S.: Need option in preferences: `autoFormatOnSave` (enabled by default).

**Comment by AnWeber** [comment]
sorry, the next time I got free time for fun coding is next weekend.
if you want to look up some code, I know 2 implentations with this feature: [beautify](https://github.com/HookyQR/VSCodeBeautify) or my own [vscode-tidyhtml](https://github.com/AnWeber/vscode-tidyhtml) (but typescript)

**Comment by mrmlnc** [comment]
Done. Please, checkout the new version of CSScomb plugin.

```
F1 → ext → Extensions: Show Outdated Extensions -> Update CSScomb plugin
```

--

Thanks for issue. :+1:

**Comment by AnWeber** [comment]
I tested the feature and it is working for css files. But I am using less files and these files gets deleted. I will create a new issue, because it also happens on command call.
