### ISSUE TITLE
csscomb error

### ISSUE THREAD

**Issue by NateLing** [mrmlnc/vscode-csscomb#54]
the problem still there.

when use csscomb.execute commend, the console output an error.

![image](https://cloud.githubusercontent.com/assets/9606668/21335599/f3abb67e-c69a-11e6-9b21-a02d3e4c3b45.png)

**Comment by mrmlnc** [comment]
Are you sure that this error is caused by this plugin?

Okay, please, give me your setting files and file that is causing this error. I'll test them in the CSSComb without plugin wrapper.

**Comment by NateLing** [comment]
env:
macos 10.12.2
vscode 1.8.1

setting 

```json
// 将设置放入此文件中以覆盖默认设置
{
    "csscomb.formatOnSave": true,
    "csscomb.preset": "csscomb",
    "csscomb.preset":{
        "color-shorthand": true,
        "leading-zero": false,
        "quotes": "single",
        "remove-empty-rulesets": true,
        "space-after-colon": 1,
        "space-before-colon": 1,
        "vendor-prefix-align": true
    },
    "csscomb.useLatestCore":true,
    // 控制在多少个字符后编辑器会自动换到下一行。将其设置为 0 则将打开视区宽度换行(自动换行)。将其设置为 -1 则将强制编辑器始终不换行。
    "editor.wrappingColumn": 0,
    // 控制已更新文件的自动保存。接受的值:“off”、"afterDelay”、"onFocusChange”(编辑器失去焦点)、"onWindowChange”(窗口失去焦点)。如果设置为“afterDelay”，则可在 "files.autoSaveDelay" 中配置延迟。
    "files.autoSave": "onWindowChange",
    // 控制打开的编辑器是否显示为预览。预览编辑器可以重新使用，直到将其保留(例如，双击或编辑)。
    "workbench.editor.enablePreview": false,
    // Turns auto fix on save on or off.
    "eslint.autoFixOnSave": true
}
```

plugin list

![image](https://cloud.githubusercontent.com/assets/9606668/21374161/9c0555ae-c75f-11e6-85af-0f5e76ca1455.png)

**Comment by mrmlnc** [comment]
I can look at your CSS file?

**Comment by NateLing** [comment]
@mrmlnc i uninstall vscode and remove all extension then reinstall vscode(1.9.0) and just install csscomb extension. i keep the setting empty. the csscomb extension does not work. and the console is no message.

**Comment by mrmlnc** [comment]
Hello, @NateLing,

Works fine for me without settings:

![screencast 2017-02-06 10-07-31](https://cloud.githubusercontent.com/assets/7034281/22637699/7c4e4c38-ec54-11e6-888e-4cc88b52eaa0.gif)

And with:

![screencast 2017-02-06 10-08-13](https://cloud.githubusercontent.com/assets/7034281/22637703/855c5a0e-ec54-11e6-8386-85779f807112.gif)

Your error not related to this plugin. The error related to [CSSComb module](https://github.com/csscomb/csscomb.js). 

You can:

1) Try to on/off `useLatestCore` option.
2) Try to check each line from your `csscomb.preset`.
3) Try to run this plugin with another CSS/Less/SCSS file.
4) Remove this plugin and use more modern [stylefmt](https://github.com/mrmlnc/vscode-stylefmt) or any plugin.
