### ISSUE TITLE
It's not working on Visual Studio Code

### ISSUE THREAD

**Issue by cassianomon** [mrmlnc/vscode-csscomb#55]
I installed it to use as I used on Sublime Text but it do nothing, I run by F1 or and also I have on my settings.json:
`"csscomb.formatOnSave": true,
    "csscomb.preset": "yandex",
    "csscomb.preset": {
        "remove-empty-rulesets": true,
        "always-semicolon": true
    },`

but still nothing :/

**Comment by mrmlnc** [comment]
Hello, @cassianomon,

This plugin does not support overriding the rules in editor preferences. CSSComb will use your latest `csscomb.preset`.

Works fine with your settings:

![2016-12-20_13-25-29](https://cloud.githubusercontent.com/assets/7034281/21346994/d50ca3be-c6b7-11e6-8460-ff6e8f170c5a.gif)

**Comment by cassianomon** [comment]
Test formatOnsave please

**Comment by mrmlnc** [comment]
What do you mean?

**Comment by cassianomon** [comment]
It's not supposed to format my code (align tabs and lines when I save) like it happens with HTML and .TS as default on Visual Studio Code?

**Comment by mrmlnc** [comment]
It's should be works fine with your settings. What behavior do you expect?

![2016-12-20_14-22-04](https://cloud.githubusercontent.com/assets/7034281/21348782/c1c91ea6-c6bf-11e6-9de8-dc6730739da4.gif)

**Comment by cassianomon** [comment]
I am not acting dumb here hehe...
As it says FORMAT on save I expected this:
![screenshot_1](https://cloud.githubusercontent.com/assets/12648633/21349052/0746ad8c-c697-11e6-8384-a88470f2c0db.png)

Since it says "CSScomb" I was expecting this extension to make as this:

http://csscomb.com/online

**Comment by mrmlnc** [comment]
This site has a built-in config. Also, this plugin has a built-in configs: https://github.com/csscomb/csscomb.js/tree/dev/config. By default, this plugin has no settings (`{}`). 

To get the same effect on your image - you need to configure this plugin. For example, using interactive builder: http://csscomb.com/config. For more details: https://github.com/csscomb/csscomb.js/blob/master/doc/options.md with description.

**Comment by cassianomon** [comment]
Found this one, it puts CSS formatting like Visual Studio Code do as default for HTML and .TS/JS...


![screenshot_1](https://cloud.githubusercontent.com/assets/12648633/21349722/9fdfe920-c69a-11e6-88d9-156ca9ccffc9.png)

Thanks for your attention.
