### ISSUE TITLE
Not activating.. how to troubleshoot?

### ISSUE THREAD

**Issue by TRE8** [mrmlnc/vscode-csscomb#57]
When I run CSSComb it doesn't execute.  I have test css code and it does not adjust like it's supposed to.  Not sure how to troubleshoot this extension.  It's installed and activated and shows up under my Command Pallete.

**Comment by mrmlnc** [comment]
By default this plugin have no config. You can create it used http://csscomb.com/config.

**Comment by TRE8** [comment]
Thanks!  Created custom file and placed in my Home directory, works.

One more thing, noticed when I add the auto-save line `"csscomb.formatOnSave": true,
 ` it doesn't execute on save.

`{
    "csscomb.formatOnSave": true,
    "remove-empty-rulesets": true,
    "always-semicolon": true,
    "color-case": "lower",
    "block-indent": "\t",
    "color-shorthand": false,
    "element-case": "lower",
    "eof-newline": true,
    "leading-zero": true,
    "quotes": "double",
    "sort-order-fallback": "abc",
    "space-before-colon": " ",
    "space-after-colon": " ",
    "space-before-combinator": " ",
    "space-after-combinator": " ",
    "space-between-declarations": "\n",
    "space-before-opening-brace": "\n",
    "space-after-opening-brace": "\n",
    "space-after-selector-delimiter": "\n",
    "space-before-selector-delimiter": "",
    "space-before-closing-brace": "\n",
    "strip-spaces": true,
    "unitless-zero": true,
    "vendor-prefix-align": true
}`

How would I enable this?

**Comment by mrmlnc** [comment]
`csscomb.xxx` options only for VS Code settings.
