### ISSUE TITLE
format of less files removes content

### ISSUE THREAD

**Issue by AnWeber** [mrmlnc/vscode-csscomb#6]
If I format a less file with the new version of csscomb (1.0.0) the content of the file is removed.

```
.foo{
    &.bar{
        display: none;
    }
}
```

> Line: 3
> Syntax: css
>ErrorMessage: Please check the validity of the block starting from line 3↵↵1 | .foo{↵2 | &.bar{↵3*| display: none;↵4 | }↵5 | }↵↵Gonzales PE version: 3.0.0-28↵Syntax: css↵CSScomb Core version: 3.0.0-3.1

**Comment by mrmlnc** [comment]
Sorry for this problem. :tada:

**Comment by AnWeber** [comment]
Great work. It works like a dream. Great extension.
