### ISSUE TITLE
Problem with useLatestCore option.

### ISSUE THREAD

**Issue by nmsmith22389** [mrmlnc/vscode-csscomb#63]
I wanted to use the useLatestCore option so I could make use of the lines-between-rules option to separate selectors. When I set it to true in my settings.json file and reloaded the window CSSComb would not work at all. I tried messing around with it to get it to work and nothing fixed it unless I disabled the useLatestCore option. With the option enabled I get no messages or errors it just simply doesn't work. If there is any way you could help at all that would be great. Even if there is a way I could modify it to get it to use 4.0.0-alpha that would be awesome! Thanks!

Also in case you need it here is my config file.
[settings.json](https://gist.github.com/nmsmith22389/41dc7e3d259f5a0d336dfff0a71419d3)

**Comment by mrmlnc** [comment]
Most likely this is a bug in CSSComb. Please, try run CSSComb `4.0.0-alpha` as npm module.

**Comment by mrmlnc** [comment]
Also see [comment](https://github.com/mrmlnc/vscode-csscomb/issues/54#issuecomment-277602084).
