### ISSUE TITLE
csscomb.useLatestCore, when true, does not do any formatting

### ISSUE THREAD

**Issue by Soft-Shock** [mrmlnc/vscode-csscomb#64]
I don't know where to check any errors on these extensions/node modules, but I would really like to use v4.0.0-alpha so that I can use the `"csscomb.preset": { "lines-between-rulesets": 1 }` configuration. v3.1.8 does not have this setting. Maybe you can give some guidance.

VS Code: 1.9.1
OS: Windows 10

Whenever I enable it and fully restart VS Code (close all Code.exe processes), no formatting happens. When I set it back to false, the formatting (except lines-between-rulesets) work.
    
Here is the config (the only thing I have been changing is `csscomb.useLatestCore`)
   
    {
    "csscomb.useLatestCore": true,

    // Use http://csscomb.com/config to generate a config
    // Reference for rules https://github.com/csscomb/csscomb.js/blob/dev/doc/options.md
    "csscomb.preset": {
        "always-semicolon": true,
        "color-case": "lower",
        "block-indent": "    ",
        "element-case": "lower",
        "eof-newline": false,
        "lines-between-rulesets": 1,
        "space-before-colon": "",
        "space-after-colon": " ",
        "space-before-combinator": " ",
        "space-after-combinator": " ",
        "space-between-declarations": "\n",
        "space-before-opening-brace": " ",
        "space-after-opening-brace": "\n",
        "space-before-selector-delimiter": "",
        "space-before-closing-brace": "\n",
        "strip-spaces": null,
        "tab-size": true,
        "unitless-zero": true,
        "vendor-prefix-align": true
    }
    }

**Comment by mrmlnc** [comment]
Hello, @Soft-Shock,

Sorry, but I am not a developer of CSSComb package (aka kernel/core package) and for me (as developer of this plugin) it's sounds like upstream issue.

Also, I see that they recently updated one of the packages that is used in CSSComb. So I'll try to rebuild the kernel of CSSComb with the new version of parser. Unlikely, but maybe this will solve some problems.

**Comment by mrmlnc** [comment]
Hmm, very strange, but I can reproduce this behavior with VS Code 1.9.1.

**Comment by mrmlnc** [comment]
WTF, I don't understand it. Works fine with debug and not work as extension from Marketplace.

**Comment by mrmlnc** [comment]
Should be fixed by `4.0.1`.

**Comment by Soft-Shock** [comment]
Okay, thanks for your help! I'll try it in the next version.
