### ISSUE TITLE
LESS: Passing ruleset to mixin  shows error.

### ISSUE THREAD

**Issue by sengfan** [mrmlnc/vscode-csscomb#65]
```desktop-and-old-ie(@rules) {
  @media screen and (min-width: 1200px) { @rules(); }
  html.lt-ie9 &                         { @rules(); }
}

header {
  background-color: blue;

  .desktop-and-old-ie({
    background-color: red;
  });
}
```

![qq 20170215235526](https://cloud.githubusercontent.com/assets/22653293/23009206/3e22a5c0-f3da-11e6-82d9-4a2ba24929a7.png)
![image](https://cloud.githubusercontent.com/assets/22653293/23009281/abf4bac0-f3da-11e6-9e4d-ab64a6acc852.png)
This an interesting error, because there are only 12 line in this less file, but shows the error is on  line #17
I found a similar fixed issue on https://github.com/csscomb/csscomb.js/issues/266

**Comment by mrmlnc** [comment]
Hello, @sengfan,

Have you tried to use `csscomb.useLatestCore` option?

Sorry, but I am not a developer of CSSComb package and for me (as developer of this plugin) it's sounds like upstream issue.

Also, I see that they recently updated one of the packages that is used in CSSComb. So I'll try to rebuild the kernel of CSSComb with the new version of parser. Unlikely, but maybe this will solve some problems.

**Comment by mrmlnc** [comment]
Well, fixed by `csscomb.useLatestCore`.

**Comment by sengfan** [comment]
yes， thank you so much!
