### ISSUE TITLE
crash when format less mixins

### ISSUE THREAD

**Issue by viko16** [mrmlnc/vscode-csscomb#7]
:cry: 
![image](https://cloud.githubusercontent.com/assets/5064777/15266643/cf945f16-19de-11e6-84be-56aabba79e04.png)

**Comment by mrmlnc** [comment]
I can see Less code that throws the exception?

**Comment by viko16** [comment]
```
.minix-logo(@img; @w; @h; @marginRight: .05rem) {
    &::before {
        content: "";
        background: url('../images/index/logo-@{img}') no-repeat;
        background-size: 100% 100%;
        width: @w;
        height: @h;
        display: inline-block;
        vertical-align: middle;
        margin-right: @marginRight;
    }
}
```

^ i think it cause

**Comment by mrmlnc** [comment]
Sorry, but this error is related to this issue https://github.com/csscomb/csscomb.js/issues/393 in CSScomb.
.

**Comment by viko16** [comment]
Oh, and thank you for your answer. :+1:
