### ISSUE TITLE
Turning off adding quotes to background URLs

### ISSUE THREAD

**Issue by MichaelTontchev** [mrmlnc/vscode-csscomb#78]
Hi,

My company has a preprocessor that requires the background URL to not have any quotes, like

`background: url(resolve/my/path/preprocessor)`

Unfortunately, it doesn't seem that this is configurable in CSScomb. Would it be possible to make this option configurable?

Alternatively, can a rule be turned off for specific lines?

Thanks!
Michael

**Comment by mrmlnc** [comment]
Hello, @MichaelTontchev ,

Most likely this is a problem of csscomb and related to [csscomb](https://github.com/csscomb/csscomb.js) repository. 

I close this issue, but we can reopen it if this problem related to my plugin.
