### ISSUE TITLE
Keybinding overrides default vscode formatter

### ISSUE THREAD

**Issue by benweet** [mrmlnc/vscode-csscomb#8]
```
{ "key": "shift+alt+f",           "command": "csscomb.processEditor",
                                     "when": "editorTextFocus" }
```

is added to the default keyboard shortcuts, which prevents the default formatter from running in non css files.

**Comment by mrmlnc** [comment]
Thanks, I delete the default key combination.

**Comment by mrmlnc** [comment]
See realese https://github.com/mrmlnc/vscode-csscomb/releases/tag/1.0.2

**Comment by benweet** [comment]
Thanks!

**Comment by CKGrafico** [comment]
The best is to be able to use this shortcut like other plugins and if is not a scss file activate default formatter
