### ISSUE TITLE
It does's working in postcss style

### ISSUE THREAD

**Issue by leenin** [mrmlnc/vscode-csscomb#81]
in
```
<style lang="postcss">
</style>

```
[CSSComb]

TypeError: Cannot read property 'syntax' of undefined

**Comment by mrmlnc** [comment]
Sorry, but this error throw CSSComb, not my plugin. This happens because `postcss` is not supported by CSSComb.

**Comment by leenin** [comment]
Could you add a setting, that can associate `lang="postcss"` to `lang="scss"`.
Because I add many plugins to postcss, the csscomb can not check syntax truely.

**Comment by mrmlnc** [comment]
Yeap, I think I can do it right now :)

**Comment by leenin** [comment]
Thanks!!!

**Comment by mrmlnc** [comment]
Fixed by `vscode-csscomb@5.1.0`.
