### ISSUE TITLE
Broken with "csscomb.preset": "yandex"

### ISSUE THREAD

**Issue by kv4sha** [mrmlnc/vscode-csscomb#83]
After update to version 5, format feature was broken.
![capture](https://user-images.githubusercontent.com/13916346/29214051-7f16c9b2-7eae-11e7-83f4-98a4202c3b4b.PNG)

**Comment by mrmlnc** [comment]
Hello, @kv4sha,

Most likely this is a CSSComb bug. This works if you run CSSComb as CLI, JS Module or maybe with something plugin/editor?

**Comment by kv4sha** [comment]
You are right, it's a bug in csscomb. Thanks

**Comment by mrmlnc** [comment]
You can create issue in the [CSSComb repository](https://github.com/csscomb/csscomb.js) and after bump CSSComb version I'll update my plugin 👍
