### ISSUE TITLE
VSCode 1.15 - TypeError: ast.remove is not a function

### ISSUE THREAD

**Issue by StfBauer** [mrmlnc/vscode-csscomb#85]
Since version VSCode 1.15 I get the following error: 

```
TypeError: ast.remove is not a function
```

Any idea?

**Comment by mrmlnc** [comment]
Hello, @StfBauer,

Now we use `csscomb@4` by default and it looks like a bug. Please, provider more description of problem and submit it to https://github.com/csscomb/csscomb.js

**Comment by StfBauer** [comment]
Forget it. ;) Figured it out was is was. Had to recreate CSSComb config. Works fine now.

**Comment by ryanbowden** [comment]
@StfBauer what was your fix? having the same issue, it's not working at all.

**Comment by MihailStar** [comment]
[https://github.com/csscomb/csscomb.js/issues/501](https://github.com/csscomb/csscomb.js/issues/501)

**Comment by StfBauer** [comment]
The fixe was to recreate the CSS Comb configuration. Navigate to [http://csscomb.com](http://csscomb.com) and click get config on top bar.
After that I saved the file and everything worked again.
