### ISSUE TITLE
CSScomb fails when i Execute 'csscomb' command in vs-code(1.15.1)

### ISSUE THREAD

**Issue by xiongcaihu** [mrmlnc/vscode-csscomb#86]
--------before -------
![image](https://user-images.githubusercontent.com/10113078/29439528-c4f5ca4a-83f0-11e7-8b71-f345e0fb1712.png)

-------doing---------
![image](https://user-images.githubusercontent.com/10113078/29439535-cd4b728a-83f0-11e7-89f7-e0647e1ddc35.png)

---------after-----------
![image](https://user-images.githubusercontent.com/10113078/29439543-e4e300f2-83f0-11e7-976c-8a96cd6c087c.png)

-----------and my config is :
![image](https://user-images.githubusercontent.com/10113078/29439552-fa608756-83f0-11e7-8f05-bea3e1974de0.png)

-------- csscomb version
![image](https://user-images.githubusercontent.com/10113078/29439573-20ca4fa8-83f1-11e7-8011-f059c48c87f2.png)

**Comment by mrmlnc** [comment]
Hello, @xiongcaihu,

This works fine if you run CSSComb as CLI, JS Module or maybe with something plugin/editor?

**Comment by mrmlnc** [comment]
Closed as outdated issue. Feel free to reopen.
