### ISSUE TITLE
Parsing error on calculation

### ISSUE THREAD

**Issue by smart-z** [mrmlnc/vscode-csscomb#87]
Csscomb is a great work, i like it very much;
"`*`" Character, "`*`" character is css hack;

Run csscomb format, in css, scss, so:
147 lines have a "`*`" character

**Can not run, please save me.**

```
[CSSComb]

Parsing error: /Users/i/Documents/oneDrive/mysteel/改版/有色铝/html/lv/css/index.css
Please check validity of the block starting from line #147
CSScomb Core version: 4.2.0

145 | .subNav dt { width: 800px; float: left; font-size: 0; }
147*| .subNav dt .red { font-size: 12px; font-weight: bold; *float: left; *padding-top: 7px; }
149 | .subNav dt ul, .subNav dt ul li { display: inline-block; font-size: 12px; *float: left; }

Syntax: css
Gonzales PE version: 3.4.7
```
**Can not run, please save me. 😭**
_oh my poor chinglish_

**Comment by mrmlnc** [comment]
Hello, @smart-z,

This is a bug of CSSComb. You can create issue in the [CSSComb repository](https://github.com/csscomb/csscomb.js) and after bump CSSComb version I'll update my plugin 👍

**Comment by smart-z** [comment]
I do not understand that about these processes.
thank you very much.
You're awesome.
