### ISSUE TITLE
TypeError: ast.remove is not a function

### ISSUE THREAD

**Issue by PleaseDont** [mrmlnc/vscode-csscomb#98]
### Environment

  * VSCode Version: 1.18.1
  * OS Version: macOS 10.13.1

### Actual behavior

An error that occurs when `"eof-newline": false`.

### Expected behavior

...

### Steps to reproduce

...

### Config

```js
// Paste your configuration here.
```

**Comment by mrmlnc** [comment]
Hello, @PleaseDont,

This is a bug of CSSComb. We use latest version of CSSComb and it can be reproduced with CSSComb as CLI. You can create issue in the [CSSComb repository](https://github.com/csscomb/csscomb.js) and after bump CSSComb version I'll update my plugin 👍

**Comment by PleaseDont** [comment]
@mrmlnc thx

**Comment by ryanbowden** [comment]
Fix is already pull requested: https://github.com/csscomb/csscomb.js/pull/552

Just waiting for it to be merged in...
